name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  precheck:
    name: Check NPM token
    runs-on: ubuntu-latest
    outputs:
      has_token: ${{ steps.check.outputs.has_token }}
    steps:
      - name: Check if NPM_TOKEN is set
        id: check
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "has_token=false" >> "$GITHUB_OUTPUT"
            echo "NPM_TOKEN is not set. Skipping publish job."
          else
            echo "has_token=true" >> "$GITHUB_OUTPUT"
          fi

  publish:
    name: Build, Test and Publish
    needs: precheck
    if: needs.precheck.outputs.has_token == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set package version from tag
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
          else
            TAG="${GITHUB_REF_NAME}"
          fi
          if [ -z "$TAG" ]; then
            echo "No tag found; cannot derive version."
            exit 1
          fi
          VERSION="${TAG#v}"
          echo "Setting package.json version to $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public
